export type LegalBlock =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

export type LegalDoc = {
  slug: "terms" | "privacy" | "cookies" | "refund" | "disclaimer";
  title: string;
  lastUpdated: string;
  intro: string;
  body: LegalBlock[];
};

function commonSections(subject: string): LegalBlock[] {
  return [
    { type: "h2", text: `Scope` },
    { type: "p", text: `This document (the "${subject}") governs your access to and use of Jobly. Placeholder content — final wording will be provided by counsel.` },
    { type: "h2", text: `Definitions` },
    { type: "ul", items: [
      `"Jobly" refers to the Jobly service, website, and applications.`,
      `"You" or "User" refers to any person who accesses or uses the service.`,
      `"Content" refers to any material displayed within or generated by the service.`,
    ] },
    { type: "h2", text: `Your responsibilities` },
    { type: "p", text: `You agree to use Jobly in good faith and in compliance with applicable law. Placeholder text — real obligations will be listed here.` },
    { type: "h3", text: `Prohibited conduct` },
    { type: "ul", items: [
      `Attempting to reverse-engineer or scrape the service`,
      `Uploading unlawful, harassing, or infringing content`,
      `Impersonating another person or entity`,
    ] },
    { type: "h2", text: `Changes to this document` },
    { type: "p", text: `We may update this ${subject} from time to time. Material changes will be announced by email or in-product notice at least 14 days before they take effect.` },
    { type: "h2", text: `Contact` },
    { type: "p", text: `Questions about this document can be sent to legal@jobly.example. We respond within one business day.` },
  ];
}

export const LEGAL_DOCS: Record<LegalDoc["slug"], LegalDoc> = {
  terms: {
    slug: "terms",
    title: "Terms of Service",
    lastUpdated: "2026-06-01",
    intro: "The rules that govern using Jobly. Read them before creating an account.",
    body: commonSections("Terms of Service"),
  },
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    lastUpdated: "2026-06-01",
    intro: "What data we collect, how we use it, and the controls you have.",
    body: [
      { type: "h2", text: "Data we collect" },
      { type: "p", text: "We collect the information you provide during onboarding (role, stack, level, location, salary preferences, email) plus basic usage telemetry. Placeholder content." },
      { type: "h2", text: "How we use it" },
      { type: "ul", items: ["Matching you to relevant roles", "Sending your daily digest", "Improving the ranking model in aggregate"] },
      { type: "h2", text: "Your rights" },
      { type: "p", text: "You can export or delete your data at any time from account settings. Placeholder — final controls will be listed here." },
      ...commonSections("Privacy Policy").slice(-4),
    ],
  },
  cookies: {
    slug: "cookies",
    title: "Cookie Policy",
    lastUpdated: "2026-06-01",
    intro: "How and why Jobly uses cookies and similar technologies.",
    body: [
      { type: "h2", text: "Types of cookies we use" },
      { type: "ul", items: ["Essential — sign-in and session", "Analytics — anonymised usage stats", "Preference — remembers filters and layout"] },
      { type: "h2", text: "Managing cookies" },
      { type: "p", text: "You can control cookies via your browser or in the in-app preferences center. Placeholder content." },
      ...commonSections("Cookie Policy").slice(-4),
    ],
  },
  refund: {
    slug: "refund",
    title: "Refund / ARL Policy",
    lastUpdated: "2026-06-01",
    intro: "How refunds and auto-renewal cancellations work for paid Jobly plans.",
    body: [
      { type: "h2", text: "Refund window" },
      { type: "p", text: "Paid subscriptions are refundable within 14 days of first purchase, no questions asked. Placeholder content." },
      { type: "h2", text: "Auto-renewal (ARL)" },
      { type: "p", text: "Subscriptions renew automatically. You can cancel anytime and continue to have access until the end of the current billing period." },
      ...commonSections("Refund Policy").slice(-4),
    ],
  },
  disclaimer: {
    slug: "disclaimer",
    title: "Disclaimer",
    lastUpdated: "2026-06-01",
    intro: "Important information about the limits of the Jobly service.",
    body: [
      { type: "h2", text: "No employment guarantee" },
      { type: "p", text: "Jobly surfaces relevant openings and provides tools to help you apply — it does not guarantee interviews, offers, or employment outcomes." },
      { type: "h2", text: "Third-party listings" },
      { type: "p", text: "Job listings originate from third-party sources. We do not control their accuracy, availability, or hiring processes." },
      ...commonSections("Disclaimer").slice(-4),
    ],
  },
};

export const LEGAL_ORDER: LegalDoc["slug"][] = ["terms", "privacy", "cookies", "refund", "disclaimer"];

export function formatLegalDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function slugifyHeading(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}