export type LegalBlock =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][] };

export type LegalDoc = {
  slug: "terms" | "privacy" | "billing" | "refund" | "cookies" | "email" | "disclaimer" | "dmca";
  title: string;
  lastUpdated: string;
  intro: string;
  body: LegalBlock[];
};

export const LEGAL_DOCS: Record<LegalDoc["slug"], LegalDoc> = {
  terms: {
    slug: "terms",
    title: "Terms of Service",
    lastUpdated: "2026-07-21",
    intro: "These Terms of Service (\"Terms\") are a binding agreement between you (\"you,\" \"user,\" \"candidate\") and NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569) (\"Jobly,\" \"we,\" \"us,\" \"our\"), governing your access to and use of the Jobly website, web application, mobile applications, and related services (collectively, the \"Service\"). By creating an account, submitting your email, subscribing, or otherwise using the Service, you agree to these Terms and to our Privacy Policy, Subscription & Billing Terms, Refund & Cancellation Policy, Service Disclaimer, Email & Communications Consent, and Cookie Policy, each incorporated by reference. If you do not agree, do not use the Service.",
    body: [
    { type: "h2", text: "1. Eligibility" },
    { type: "p", text: "You must be at least 18 years old and able to form a binding contract. By using the Service you represent that you meet these requirements and that the information you provide is accurate and complete." },
    { type: "h2", text: "2. Description of the Service" },
    { type: "p", text: "Jobly is a job-discovery service for candidates. You create a profile (role, stack, level, location, salary range) and receive an email digest of relevant job listings with a personalized \"match score,\" aggregated from permitted third-party job APIs, publicly available employment data sources, and other authorized third-party sources. The Service also offers an application tracker and reminders. Match scores, rankings, and filtering (including attempts to identify duplicate, inactive, ghost, or potentially fraudulent (\"scam\") job listings) are informational estimates only; see the Service Disclaimer. We do not guarantee that all duplicate, inactive, fraudulent, misleading, or expired job listings will be identified or removed from the Service." },
    { type: "h2", text: "3. What Jobly is not" },
    { type: "p", text: "Jobly is not an employer, recruiter, staffing agency, or the source of the job listings it surfaces. We do not submit applications on your behalf, do not guarantee interviews, offers, or employment, and are not a party to any relationship between you and any employer. Listings originate from third parties and may be inaccurate, expired, filled, or removed. We do not verify the identity, legitimacy, hiring practices, financial condition, or legal compliance of employers or other third parties whose listings appear through the Service." },
    { type: "p", text: "We do not guarantee that employers will review, respond to, or consider any application submitted through links provided by the Service." },
    { type: "h2", text: "4. Accounts and security" },
    { type: "p", text: "You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. Notify us immediately at legal@jobly.careers of any unauthorized use. We are not liable for losses arising from your failure to safeguard your credentials." },
    { type: "h2", text: "5. Email and notifications" },
    { type: "p", text: "The Service is email-first: by providing your email and using the Service you consent to receive the job digest and related transactional and service messages, as described in the Email & Communications Consent and Privacy Policy. You can unsubscribe from marketing messages and manage digest frequency at any time; certain transactional messages are necessary to provide the Service. We do not guarantee the timing or successful delivery of emails, which may be delayed, filtered, or blocked by third-party email providers." },
    { type: "h2", text: "6. Subscriptions, trials, and billing" },
    { type: "p", text: "The Service offers a free tier and paid subscriptions (\"Pro\"), including a trial period. Pricing, billing cycles, auto-renewal, trial conversion, cancellation, and the \"found a job\" pause are described in the Subscription & Billing Terms and Refund & Cancellation Policy, which form part of these Terms. Payments are processed by third parties (e.g., Stripe on the web; Apple App Store and Google Play for in-app purchases); their terms also apply." },
    { type: "h2", text: "7. Acceptable use" },
    { type: "p", text: "You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to the Service or other users' data; (c) scrape, crawl, reverse engineer, or interfere with the Service or its data sources; (d) use the Service to send spam or to mass-apply or auto-apply to jobs on your behalf via third-party sites in violation of those sites' terms; (e) resell or commercially exploit the Service without our permission; (f) upload malicious code or unlawful content; (g) create multiple accounts to abuse, circumvent, or interfere with the Service; or (h) collect, harvest, or otherwise extract employer, recruiter, or user information from the Service." },
    { type: "h2", text: "8. Intellectual property" },
    { type: "p", text: "The Service, including its software, design, text, and trademarks (excluding third-party job data and marks), is owned by Jobly or its licensors and protected by intellectual-property laws. We grant you a limited, revocable, non-transferable license to use the Service for personal, non-commercial job-search purposes in accordance with these Terms. Company names, brand names, and job-listing content belong to their respective owners and are used for identification only; Jobly is not affiliated with or endorsed by them. You retain ownership of any resumes, profile information, cover letters, and other content you submit to the Service (\"User Content\"). You grant Jobly a worldwide, non-exclusive, royalty-free license to host, store, process, reproduce, analyze, and use your User Content solely for the purpose of providing, maintaining, and improving the Service." },
    { type: "h2", text: "9. Third-party job data and sources" },
    { type: "p", text: "Job listings are aggregated from permitted third-party APIs and public ATS feeds and are provided \"as is.\" We do not control, verify, or guarantee the accuracy, legality, availability, or timeliness of listings, and we are not responsible for the content or practices of employers or source platforms. Job listings may be modified, suspended, filled, or removed by employers or source platforms at any time without notice. Your use of any third-party site (including applying to a job) is governed by that site's terms." },
    { type: "h2", text: "10. No employment or professional advice" },
    { type: "p", text: "Match scores, rankings, and career-related suggestions are informational and automated; they are not recommendations, guarantees, or professional, career, legal, or financial advice, and do not guarantee employment outcomes. Users are solely responsible for evaluating job opportunities and deciding whether to apply for any position. You are solely responsible for your application decisions. See the Service Disclaimer. Users are solely responsible for reviewing and verifying any resumes, cover letters, or other application materials generated or assisted by the Service before using or submitting them." },
    { type: "h2", text: "11. Disclaimers of warranties" },
    { type: "p", text: "To the maximum extent permitted by law, the Service is provided \"as is\" and \"as available\" without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, accuracy, and non-infringement. We do not warrant that the Service will be uninterrupted or error-free, that any listing is genuine or current, or that employers are legitimate, actively hiring, or will respond to applications." },
    { type: "h2", text: "12. Limitation of liability" },
    { type: "p", text: "To the maximum extent permitted by law, Jobly and its officers, employees, and suppliers will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for lost profits, data, employment opportunities, or goodwill, or for any decisions made in reliance on listings or match scores. Our total aggregate liability for any claim arising out of or relating to the Service will not exceed the greater of (a) the amount you paid us in the twelve (12) months before the event giving rise to the claim, or (b) USD 100. Some jurisdictions do not allow certain limitations, so some of the above may not apply to you." },
    { type: "h2", text: "13. Indemnification" },
    { type: "p", text: "You agree to indemnify and hold harmless Jobly from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the Service, your content, or your breach of these Terms." },
    { type: "h2", text: "14. Termination" },
    { type: "p", text: "You may stop using the Service and cancel your subscription at any time. Termination of your account does not automatically entitle you to a refund, except as provided in our Refund Policy. We may suspend or terminate your access if you breach these Terms or if required by law. Provisions that by their nature should survive (e.g., IP, disclaimers, limitation of liability, dispute resolution) will survive termination." },
    { type: "h2", text: "15. Changes to the Service and Terms" },
    { type: "p", text: "We may modify the Service or these Terms. If we make material changes, we will provide notice (e.g., by email or in-app). Continued use after changes take effect constitutes acceptance. If you do not agree, stop using the Service." },
    { type: "h2", text: "16. Governing law and dispute resolution" },
    { type: "p", text: "These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-laws rules. Any dispute arising out of or relating to these Terms or the Service shall be resolved by binding individual arbitration administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules." },
    { type: "p", text: "YOU AND JOBLY AGREE TO WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE PROCEEDING, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW." },
    { type: "p", text: "Nothing in this Section limits either party's right to bring an individual claim in a qualifying small claims court where permitted by applicable law. For EU/UK consumers, mandatory local consumer protections are not waived." },
    { type: "h2", text: "17. Miscellaneous" },
    { type: "p", text: "These Terms, together with the incorporated policies, are the entire agreement between you and us regarding the Service. If any provision is held unenforceable, the remaining provisions remain in effect. Our failure to enforce a provision is not a waiver. Section headings are for convenience only and do not affect the interpretation of these Terms. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets." },
    { type: "h2", text: "18. Contact" },
    { type: "p", text: "NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569. Questions: hello@jobly.careers." },
    ],
  },
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    lastUpdated: "2026-07-20",
    intro: "This Privacy Policy explains how NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569) (\"Jobly,\" \"we,\" \"us\"), collects, uses, shares, and protects personal information when you use the Jobly website, web application, and mobile apps (the \"Service\"). By using the Service you agree to this Policy.",
    body: [
    { type: "h2", text: "1. Information we collect" },
    { type: "p", text: "Account information: name, email, password (hashed)." },
    { type: "p", text: "Job-search profile: role, tech stack/specialization, level, location/remote preference, salary range, and notification preferences." },
    { type: "p", text: "Resume / CV data (Phase 2, if you upload it): the contents of your resume and derived data (skills, experience). Provided only with your explicit consent; may include additional personal details you choose to include." },
    { type: "p", text: "Application-tracker data: jobs you save, statuses, notes, reminders." },
    { type: "p", text: "Usage and analytics data: pages viewed, features used, events, email engagement (opens, clicks), session recordings/heatmaps, approximate location derived from IP." },
    { type: "p", text: "Device and technical data: device type, OS, browser, identifiers, and, for the app, push tokens." },
    { type: "p", text: "Marketing/attribution data: campaign and referral information (e.g., UTM parameters, ad attribution)." },
    { type: "p", text: "Payment data: processed by our payment providers; we receive limited billing details (e.g., plan, status, last four digits) but not full card numbers." },
    { type: "h2", text: "2. How we use information" },
    { type: "p", text: "Provide and operate the Service: build your profile, match jobs, generate the digest and match scores, run the tracker." },
    { type: "p", text: "Send the email digest and transactional messages; with your consent where required, marketing." },
    { type: "p", text: "Create and secure your account and prevent fraud." },
    { type: "p", text: "Process subscriptions, trials, and payments." },
    { type: "p", text: "Analyze usage to improve matching and the product." },
    { type: "p", text: "Comply with legal obligations and enforce our Terms." },
    { type: "h2", text: "3. Legal bases (EEA/UK users)" },
    { type: "p", text: "Where GDPR/UK GDPR applies, we process personal data on the bases of: performance of a contract (providing the Service); your consent (e.g., resume upload, certain cookies, marketing); our legitimate interests (securing and improving the Service); and compliance with legal obligations. You may withdraw consent at any time." },
    { type: "h2", text: "4. How we share information" },
    { type: "p", text: "We do not sell your personal information for money. We share it with service providers (\"processors\") that help us run the Service, under contracts limiting their use, including:" },
    { type: "p", text: "Email/notifications: [ESP, e.g., Postmark] (digest and transactional email)." },
    { type: "p", text: "Payments: Stripe (web); Apple App Store, Google Play, and RevenueCat (in-app subscriptions)." },
    { type: "p", text: "Infrastructure & database: Supabase (auth/database), [hosting provider]." },
    { type: "p", text: "Analytics & product: Google Analytics 4, Amplitude, Microsoft Clarity." },
    { type: "p", text: "Attribution: AppsFlyer, and ad platforms (e.g., Google) for measurement." },
    { type: "p", text: "Job listings come from third-party sources (e.g., Adzuna, Jooble, USAJobs, and public ATS feeds such as Greenhouse/Lever/Ashby); when you click through or apply, you interact with those third parties under their terms. We may also disclose information to comply with law, enforce our Terms, protect rights and safety, or in connection with a merger, acquisition, or sale of assets. Some analytics/advertising activities may be considered \"sharing\" or \"sale\" under certain US state laws; see Section 8." },
    { type: "h2", text: "5. Cookies and similar technologies" },
    { type: "p", text: "We use cookies and similar technologies as described in our Cookie Policy. Where required, we obtain consent through a cookie banner." },
    { type: "h2", text: "6. Data retention" },
    { type: "p", text: "We retain personal information for as long as your account is active and as needed to provide the Service, then for a reasonable period to comply with legal obligations, resolve disputes, and enforce agreements. You can request deletion (Section 8); resume data can be deleted on request or by removing it in your account. Some data may be retained where legally required." },
    { type: "h2", text: "7. Security" },
    { type: "p", text: "We use administrative, technical, and organizational safeguards (e.g., encryption in transit, access controls). No system is completely secure; we cannot guarantee absolute security." },
    { type: "h2", text: "8. Your privacy rights" },
    { type: "p", text: "US (including California — CCPA/CPRA): depending on your state, you may have the right to know/access, delete, correct, and to opt out of the \"sale\" or \"sharing\" of personal information and of targeted advertising, and not to be discriminated against for exercising these rights. To opt out, use [\"Do Not Sell or Share My Personal Information\" link/mechanism] or contact privacy@jobly.careers. We honor recognized opt-out preference signals (e.g., Global Privacy Control) where required." },
    { type: "p", text: "EEA/UK (GDPR): you may have the right to access, rectify, erase, restrict, or object to processing, to data portability, and to withdraw consent. You may also lodge a complaint with your supervisory authority." },
    { type: "p", text: "To exercise rights, contact privacy@jobly.careers. We will verify your request as required by law." },
    { type: "h2", text: "9. International data transfers" },
    { type: "p", text: "We may process and store information in the United States, the United Kingdom, and other countries. Where required, we use appropriate safeguards (e.g., Standard Contractual Clauses / UK IDTA) for transfers of EEA/UK personal data." },
    { type: "h2", text: "10. Children" },
    { type: "p", text: "The Service is not directed to children and is intended for users 18 and older. We do not knowingly collect personal information from children. If you believe a child has provided data, contact privacy@jobly.careers and we will delete it." },
    { type: "h2", text: "11. Changes to this Policy" },
    { type: "p", text: "We may update this Policy. We will post the new version with an updated date and, for material changes, provide additional notice. Continued use after the effective date constitutes acceptance." },
    { type: "h2", text: "12. Contact" },
    { type: "p", text: "NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569. Privacy contact / DPO (if applicable): privacy@jobly.careers." },
    ],
  },
  billing: {
    slug: "billing",
    title: "Subscription & Billing Terms",
    lastUpdated: "2026-07-20",
    intro: "These Subscription & Billing Terms are part of the Jobly Terms of Service (offered by NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569)) and describe our plans, trials, automatic renewal, pause, and cancellation.",
    body: [
    { type: "h2", text: "1. Free tier and paid plans" },
    { type: "p", text: "Jobly offers a free tier (e.g., a weekly digest without match score and without the tracker) and a paid subscription (\"Pro\") with expanded features (e.g., daily digest, match score, application tracker, \"found a job\" pause). The features, prices, and billing periods of each plan are presented to you at the point of purchase and may change as described in Section 7." },
    { type: "h2", text: "2. Trial" },
    { type: "p", text: "We may offer a trial period (e.g., 3 days) of Pro. Before the trial begins, we will clearly disclose the trial length, the price and billing period that will apply after the trial, and how to cancel. Your paid subscription will begin automatically at the end of the trial and you will be charged the disclosed amount unless you cancel before the trial ends. You must affirmatively agree to these terms before the trial converts to a paid subscription." },
    { type: "h2", text: "3. Automatic renewal (auto-renewal disclosure)" },
    { type: "p", text: "Paid subscriptions automatically renew at the end of each billing period (monthly, quarterly, semi-annual, or annual, as selected) until you cancel. At the point of sale we will clearly and conspicuously disclose: (a) that the subscription continues until cancelled; (b) the recurring amount and billing frequency; (c) the renewal/cancellation terms; and (d) how to cancel. By subscribing, you authorize us (and our payment processors) to charge your payment method the then-current amount at the start of each billing period." },
    { type: "h2", text: "4. Renewal reminder" },
    { type: "p", text: "Where required by law (and as a default good practice), we will send a reminder before your first charge following a trial and before certain renewals, including the amount, date, and a link or instructions to cancel." },
    { type: "h2", text: "5. Cancellation (easy cancellation / \"click-to-cancel\")" },
    { type: "p", text: "You can cancel at any time. Cancellation is available through the same medium you used to subscribe and takes no more than two (2) steps: for web subscriptions, in your account under Manage Subscription → Cancel; for in-app subscriptions, through your Apple App Store or Google Play account settings. We do not require you to call, chat, or take additional steps beyond those needed to cancel. Cancellation stops future renewals; you retain Pro access until the end of the current paid period unless otherwise required by law." },
    { type: "h2", text: "6. Pause (\"found a job\")" },
    { type: "p", text: "Instead of cancelling, you may pause your subscription (e.g., for up to 6 months) when you have found a job. During a pause, you are not charged; billing resumes when the pause ends unless you cancel. Pause terms (duration, availability, and any re-activation notice) are shown at the time you choose them." },
    { type: "h2", text: "7. Prices, changes, and taxes" },
    { type: "p", text: "Prices are shown at checkout in your local currency where available and are exclusive of taxes unless stated. We may change prices; we will give advance notice as required by law, and changes apply to the next billing period after notice. Applicable taxes may be added based on your location." },
    { type: "h2", text: "8. Payment methods and failed payments" },
    { type: "p", text: "Web payments are processed by Stripe; in-app purchases are processed by Apple App Store or Google Play (managed via RevenueCat). You are responsible for keeping your payment method valid. If a charge fails, we may retry and/or suspend Pro access until payment succeeds." },
    { type: "h2", text: "9. Refunds" },
    { type: "p", text: "Refunds are governed by our Refund & Cancellation Policy. In-app purchases are subject to the applicable app store's refund process." },
    { type: "h2", text: "10. Contact" },
    { type: "p", text: "Billing questions: hello@jobly.careers. NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569." },
    ],
  },
  refund: {
    slug: "refund",
    title: "Refund & Cancellation Policy",
    lastUpdated: "2026-07-20",
    intro: "This Policy explains how cancellations and refunds work for Jobly subscriptions (offered by NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569)). It is part of our Terms of Service and should be read with the Subscription & Billing Terms.",
    body: [
    { type: "h2", text: "1. Cancelling your subscription" },
    { type: "p", text: "You may cancel at any time. Cancelling stops future renewals; you keep Pro access until the end of your current paid period. See the Subscription & Billing Terms for step-by-step cancellation (web: Manage Subscription → Cancel; in-app: through the App Store or Google Play)." },
    { type: "h2", text: "2. Pause instead of cancel" },
    { type: "p", text: "If you found a job, you can pause your subscription (e.g., up to 6 months) instead of cancelling; you are not charged during the pause. See the Subscription & Billing Terms." },
    { type: "h2", text: "3. Trials" },
    { type: "p", text: "If you cancel during a trial before it converts, you will not be charged. If you do not cancel before the trial ends, the subscription begins and the disclosed fee applies." },
    { type: "h2", text: "4. Refunds — general" },
    { type: "p", text: "Except as required by law or expressly stated here, subscription fees are non-refundable, and we do not provide refunds or credits for partial billing periods or unused time after a renewal. We may, at our discretion, grant refunds in individual cases (e.g., accidental duplicate charges or a documented billing error)." },
    { type: "h2", text: "5. In-app purchases (Apple / Google)" },
    { type: "p", text: "If you purchased through the Apple App Store or Google Play, your purchase is subject to that store's terms, and refund requests must be made to Apple or Google through their processes; we cannot directly refund store-processed payments." },
    { type: "h2", text: "6. Statutory rights" },
    { type: "p", text: "EEA/UK consumers: you may have a statutory right to withdraw within 14 days of purchase. For digital services that begin during this period, you may be asked to consent to immediate performance and acknowledge that you lose the withdrawal right once the service has been fully performed; where the service is only partly performed, a proportionate amount may be payable. Nothing here limits mandatory consumer rights." },
    { type: "p", text: "US consumers: some states provide additional cancellation or refund rights (including under automatic-renewal laws). Nothing here limits those rights." },
    { type: "h2", text: "7. Chargebacks" },
    { type: "p", text: "If you believe a charge is incorrect, please contact us first at hello@jobly.careers so we can help. Initiating a chargeback without contacting us may result in suspension of your account while the dispute is resolved." },
    { type: "h2", text: "8. How to request a refund" },
    { type: "p", text: "For web (Stripe) purchases, contact hello@jobly.careers with your account email and the charge details. For app-store purchases, use Apple's or Google's refund process." },
    { type: "h2", text: "9. Contact" },
    { type: "p", text: "NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569. Billing: hello@jobly.careers." },
    ],
  },
  cookies: {
    slug: "cookies",
    title: "Cookie Policy",
    lastUpdated: "2026-07-20",
    intro: "Cookies and similar technologies (e.g., local storage, SDKs, pixels) are small files or identifiers stored on your device that help a website or app function, remember preferences, and understand usage. This Policy explains how Jobly (NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569)) uses them on our website and web application. It supplements our Privacy Policy.",
    body: [
    { type: "h2", text: "1. What are cookies" },
    { type: "h2", text: "2. Categories we use" },
    { type: "p", text: "Strictly necessary — required for the Service to work (e.g., authentication/session via Supabase, security, payment flows via Stripe). These cannot be switched off." },
    { type: "p", text: "Functional — remember your preferences and settings (e.g., digest frequency)." },
    { type: "p", text: "Analytics / performance — help us understand usage and improve matching and UX." },
    { type: "p", text: "Marketing / attribution — measure campaigns and attribute signups/installs." },
    { type: "h2", text: "3. Cookies and tools we use" },
    { type: "table", headers: ["Tool / provider", "Category", "Purpose"], rows: [
      ["Supabase (auth/session)", "Strictly necessary", "Keep you logged in and secure your session."],
      ["Stripe", "Strictly necessary", "Process payments and prevent fraud."],
      ["Google Analytics 4", "Analytics", "Measure traffic, conversions, and feature usage."],
      ["Amplitude", "Analytics", "Product analytics: funnels, retention, events."],
      ["Microsoft Clarity", "Analytics", "Session recordings and heatmaps to improve UX."],
      ["AppsFlyer", "Marketing / attribution", "Attribute campaigns and measure signups/installs."],
      ["Ad platforms (e.g., Google)", "Marketing / attribution", "Campaign measurement and, where enabled, advertising."],
    ] },
    { type: "p", text: "The exact cookies, durations, and providers are finalized after a technical cookie audit and reflected in the consent tool." },
    { type: "h2", text: "4. Consent" },
    { type: "p", text: "Where required (e.g., for EEA/UK visitors), we request your consent before setting non-essential cookies through a cookie banner, and you can accept, reject, or customize your choices. Strictly necessary cookies are set without consent because the Service cannot function without them. In the US, you can exercise opt-out rights for \"sale\"/\"sharing\" and targeted advertising as described in our Privacy Policy (including recognized opt-out preference signals where applicable)." },
    { type: "h2", text: "5. Managing cookies" },
    { type: "p", text: "You can change your consent choices at any time via [cookie settings link/mechanism]. You can also control cookies through your browser settings (blocking or deleting cookies may affect functionality). Mobile identifiers can be limited through your device's OS settings." },
    { type: "h2", text: "6. Changes" },
    { type: "p", text: "We may update this Policy to reflect changes in the tools we use or in the law. We will post the updated version with a new date." },
    { type: "h2", text: "7. Contact" },
    { type: "p", text: "NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569. Questions: privacy@jobly.careers." },
    ],
  },
  email: {
    slug: "email",
    title: "Email & Communications Consent",
    lastUpdated: "2026-07-20",
    intro: "Jobly is an email-first service. This notice explains what messages we send, how you consent, and how you control them. It supplements our Privacy Policy and Terms of Service.",
    body: [
    { type: "h2", text: "1. Types of messages" },
    { type: "p", text: "Job digest (core service): the periodic email listing matched jobs with your match score. This is the primary purpose of the Service." },
    { type: "p", text: "Transactional / service messages: account, security, billing, trial/renewal reminders, cancellation and pause confirmations. These are necessary to provide the Service and are sent regardless of marketing preferences." },
    { type: "p", text: "Marketing messages (optional): product tips, offers, re-activation (e.g., after a \"found a job\" pause). Sent only where permitted and subject to opt-out." },
    { type: "h2", text: "2. Consent" },
    { type: "p", text: "By submitting your email and using the Service, you agree to receive the job digest and transactional messages. Where required (e.g., for EEA/UK users or for marketing email), we rely on your consent, which we may collect via a clear opt-in (and, where used, double opt-in confirmation). You can withdraw consent to marketing at any time without affecting transactional messages needed to run the Service." },
    { type: "h2", text: "3. Frequency and preferences" },
    { type: "p", text: "You control digest frequency (e.g., daily or weekly) and can pause notifications in your account settings. Changing frequency or pausing does not cancel your subscription." },
    { type: "h2", text: "4. Unsubscribe (CAN-SPAM)" },
    { type: "p", text: "Every marketing and digest email includes a working unsubscribe link and the sender's valid physical postal address, and uses accurate \"from,\" \"to,\" and subject lines, in accordance with the US CAN-SPAM Act. We honor unsubscribe requests promptly. You may still receive necessary transactional messages after unsubscribing from marketing." },
    { type: "h2", text: "5. Push notifications (app)" },
    { type: "p", text: "If you use our mobile app, you can opt in to push notifications and control them through your device's operating-system settings." },
    { type: "h2", text: "6. SMS (if offered in future)" },
    { type: "p", text: "We do not send SMS at launch. If we introduce an SMS channel, we will obtain separate opt-in consent as required (e.g., under the US TCPA) and provide STOP-to-unsubscribe instructions." },
    { type: "h2", text: "7. Deliverability providers" },
    { type: "p", text: "Emails are sent through our email service provider ([ESP, e.g., Postmark]) acting as our processor, as described in the Privacy Policy. Digest and transactional email is sent from alerts@jobly.careers and no-reply@jobly.careers." },
    { type: "h2", text: "8. Contact" },
    { type: "p", text: "Questions about communications: privacy@jobly.careers or hello@jobly.careers. Sender: NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569." },
    ],
  },
  disclaimer: {
    slug: "disclaimer",
    title: "Service Disclaimer",
    lastUpdated: "2026-07-20",
    intro: "This Disclaimer applies to the Jobly service offered by NORELIX LIMITED, trading as \"Jobly\" (Company No. 817569).",
    body: [
    { type: "h2", text: "1. Informational purposes only" },
    { type: "p", text: "Jobly surfaces job listings and generates match scores, rankings, filters (including ghost-job/scam filtering), and career-related suggestions (collectively, \"Outputs\"). All Outputs are for general informational purposes only and are automated estimates. They are not recommendations, guarantees, or professional, career, legal, or financial advice." },
    { type: "h2", text: "2. No guarantee of employment" },
    { type: "p", text: "Jobly does not guarantee that you will receive interviews, offers, or employment, that any listing is genuine, current, or still open, or that a match score reflects your actual suitability. Hiring decisions are made solely by employers, over whom we have no control." },
    { type: "h2", text: "3. Jobly is not an employer or recruiter" },
    { type: "p", text: "Jobly is a discovery tool, not an employer, recruiter, staffing agency, or career counselor, and is not a party to any application, interview, or employment relationship. We do not submit applications on your behalf; you decide which jobs to apply to and you apply through the employer or source platform." },
    { type: "h2", text: "4. Third-party listings and data accuracy" },
    { type: "p", text: "Listings are aggregated from third-party APIs and public ATS feeds and may be inaccurate, outdated, duplicated, filled, or fraudulent despite our filtering. Our ghost-job and scam filters are heuristic and may not catch every problematic listing or may down-rank legitimate ones. Always verify a listing and employer independently before applying, sharing personal information, or making payments. Never pay a prospective employer or provide bank/payment details to obtain a job." },
    { type: "h2", text: "5. Match score methodology" },
    { type: "p", text: "Match scores are produced by automated rules (and, later, models) based on the profile you provide and available listing data. They are approximate, may be wrong, and should not be the sole basis for your decisions." },
    { type: "h2", text: "6. Your responsibility" },
    { type: "p", text: "You are solely responsible for evaluating opportunities, the accuracy of your profile and any resume you provide, your application decisions, and your interactions with employers and third-party sites." },
    { type: "h2", text: "7. Limitation of liability" },
    { type: "p", text: "To the maximum extent permitted by law, Jobly is not liable for any loss or damage arising from your reliance on any Output or listing, from fraudulent or inaccurate listings, or from any employer's conduct. This Disclaimer supplements, and is subject to, the limitation of liability in our Terms of Service." },
    { type: "h2", text: "8. Contact" },
    { type: "p", text: "NORELIX LIMITED · trading as Jobly\nThe Black Church, St Mary’s Place,\nDublin 7, D07 P4AX, Ireland\nCompany No. 817569. Questions: hello@jobly.careers." },
    ],
  },
};

export const LEGAL_ORDER: LegalDoc["slug"][] = ["terms", "privacy", "billing", "refund", "cookies", "email", "disclaimer"];

export function formatLegalDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function slugifyHeading(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
