export const ROLES = [
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "iOS Engineer",
  "Android Engineer",
  "Software Engineer",
  "Staff Engineer",
  "Engineering Manager",
  "Tech Lead",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Security Engineer",
  "QA Engineer",
  "Test Automation Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Analytics Engineer",
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "Research Engineer",
  "Product Manager",
  "Technical Product Manager",
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "UX Researcher",
  "Design Engineer",
  "Solutions Architect",
  "Systems Architect",
  "Database Administrator",
  "Embedded Engineer",
  "Firmware Engineer",
  "Game Developer",
  "Blockchain Engineer",
  "Developer Advocate",
  "Technical Writer",
  "IT Support Engineer",
];

export const LEVELS = ["Junior", "Mid", "Senior", "Lead"];

export const COMMON_STACKS = [
  "React",
  "Node.js",
  "TypeScript",
  "JavaScript",
  "Python",
  "SQL",
  "PostgreSQL",
  "AWS",
  "Docker",
  "Figma",
  "Git",
];

export const ROLE_STACKS: Record<string, string[]> = {
  "Frontend Engineer": [
    "React",
    "Next.js",
    "Vue",
    "Angular",
    "Svelte",
    "TypeScript",
    "JavaScript",
    "HTML/CSS",
    "Tailwind CSS",
    "Webpack",
    "Vite",
    "Figma",
    "Storybook",
    "Jest",
    "Cypress",
  ],
  "Backend Engineer": [
    "Node.js",
    "Python",
    "Go",
    "Java",
    "Ruby",
    "C#",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "GraphQL",
    "REST API",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "Kafka",
  ],
  "Full Stack Engineer": [
    "React",
    "Next.js",
    "Node.js",
    "TypeScript",
    "JavaScript",
    "Python",
    "PostgreSQL",
    "MongoDB",
    "GraphQL",
    "AWS",
    "Docker",
    "Kubernetes",
    "Redis",
  ],
  "Mobile Engineer": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Java",
    "iOS",
    "Android",
    "Firebase",
  ],
  "iOS Engineer": [
    "Swift",
    "Objective-C",
    "SwiftUI",
    "UIKit",
    "Xcode",
    "Core Data",
    "Combine",
    "Firebase",
  ],
  "Android Engineer": [
    "Kotlin",
    "Java",
    "Android Jetpack",
    "Compose",
    "Firebase",
    "Room",
    "Gradle",
  ],
  "Software Engineer": [
    "React",
    "Node.js",
    "TypeScript",
    "Python",
    "Go",
    "PostgreSQL",
    "AWS",
    "Docker",
    "Kubernetes",
    "Git",
  ],
  "Staff Engineer": [
    "React",
    "Node.js",
    "TypeScript",
    "Python",
    "Go",
    "Java",
    "PostgreSQL",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "Kafka",
    "Terraform",
  ],
  "Engineering Manager": [
    "Jira",
    "Confluence",
    "Notion",
    "GitHub",
    "Figma",
    "Lovable",
    "Google Analytics",
    "Amplitude",
    "Slack",
  ],
  "Tech Lead": [
    "React",
    "Node.js",
    "TypeScript",
    "Python",
    "PostgreSQL",
    "AWS",
    "Docker",
    "Kubernetes",
    "GitHub",
    "Figma",
    "Lovable",
  ],
  "DevOps Engineer": [
    "AWS",
    "GCP",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Python",
    "Go",
    "Bash",
    "Prometheus",
    "Grafana",
  ],
  "Site Reliability Engineer": [
    "AWS",
    "GCP",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Python",
    "Go",
    "Bash",
    "Prometheus",
    "Grafana",
  ],
  "Platform Engineer": [
    "AWS",
    "GCP",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Python",
    "Go",
    "Bash",
    "Prometheus",
    "Grafana",
  ],
  "Cloud Engineer": [
    "AWS",
    "GCP",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Python",
    "Go",
    "Bash",
    "Prometheus",
    "Grafana",
  ],
  "Security Engineer": [
    "Python",
    "Go",
    "Kali Linux",
    "Wireshark",
    "Burp Suite",
    "OWASP",
    "SIEM",
    "AWS",
    "Docker",
    "HashiCorp Vault",
  ],
  "QA Engineer": [
    "Selenium",
    "Cypress",
    "Playwright",
    "Jest",
    "Postman",
    "GitHub Actions",
    "CI/CD",
    "Python",
    "JavaScript",
    "TypeScript",
  ],
  "Test Automation Engineer": [
    "Selenium",
    "Cypress",
    "Playwright",
    "Jest",
    "Postman",
    "GitHub Actions",
    "CI/CD",
    "Python",
    "JavaScript",
    "TypeScript",
  ],
  "Data Engineer": [
    "Python",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "Snowflake",
    "BigQuery",
    "Apache Spark",
    "Kafka",
    "Airflow",
    "dbt",
    "AWS",
    "GCP",
    "Docker",
    "Tableau",
    "Power BI",
    "Excel",
    "Pandas",
  ],
  "Data Scientist": [
    "Python",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "Snowflake",
    "BigQuery",
    "Apache Spark",
    "Kafka",
    "Airflow",
    "dbt",
    "AWS",
    "GCP",
    "Docker",
    "Tableau",
    "Power BI",
    "Excel",
    "Pandas",
  ],
  "Data Analyst": [
    "Python",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "Snowflake",
    "BigQuery",
    "Apache Spark",
    "Kafka",
    "Airflow",
    "dbt",
    "AWS",
    "GCP",
    "Docker",
    "Tableau",
    "Power BI",
    "Excel",
    "Pandas",
  ],
  "Analytics Engineer": [
    "Python",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "Snowflake",
    "BigQuery",
    "Apache Spark",
    "Kafka",
    "Airflow",
    "dbt",
    "AWS",
    "GCP",
    "Docker",
    "Tableau",
    "Power BI",
    "Excel",
    "Pandas",
  ],
  "Machine Learning Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Jupyter",
    "Pandas",
    "NumPy",
    "SQL",
    "PostgreSQL",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "MLflow",
    "LangChain",
  ],
  "AI Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Jupyter",
    "Pandas",
    "NumPy",
    "SQL",
    "PostgreSQL",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "MLflow",
    "LangChain",
  ],
  "MLOps Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Jupyter",
    "Pandas",
    "NumPy",
    "SQL",
    "PostgreSQL",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "MLflow",
    "LangChain",
  ],
  "Research Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "Jupyter",
    "Pandas",
    "NumPy",
    "SQL",
    "PostgreSQL",
    "AWS",
    "GCP",
    "Docker",
    "Kubernetes",
    "MLflow",
    "LangChain",
  ],
  "Product Manager": [
    "Jira",
    "Confluence",
    "Notion",
    "Airtable",
    "Figma",
    "Lovable",
    "Miro",
    "Google Analytics",
    "Amplitude",
    "Mixpanel",
    "Excel",
  ],
  "Technical Product Manager": [
    "Jira",
    "Confluence",
    "Notion",
    "Airtable",
    "Figma",
    "Lovable",
    "Miro",
    "Google Analytics",
    "Amplitude",
    "Mixpanel",
    "Excel",
  ],
  "Product Designer": [
    "Figma",
    "Lovable",
    "Sketch",
    "Adobe XD",
    "Webflow",
    "Framer",
    "Miro",
    "Notion",
    "InVision",
    "Principle",
    "After Effects",
  ],
  "UX Designer": [
    "Figma",
    "Lovable",
    "Sketch",
    "Adobe XD",
    "Webflow",
    "Framer",
    "Miro",
    "Notion",
    "InVision",
    "Principle",
    "After Effects",
  ],
  "UI Designer": [
    "Figma",
    "Lovable",
    "Sketch",
    "Adobe XD",
    "Webflow",
    "Framer",
    "Miro",
    "Notion",
    "InVision",
    "Principle",
    "After Effects",
  ],
  "Design Engineer": [
    "Figma",
    "Lovable",
    "Sketch",
    "Adobe XD",
    "Webflow",
    "Framer",
    "Miro",
    "Notion",
    "InVision",
    "Principle",
    "After Effects",
  ],
  "UX Researcher": [
    "Miro",
    "Notion",
    "Figma",
    "Lovable",
    "UserTesting",
    "Hotjar",
    "Google Analytics",
    "Excel",
  ],
  "Solutions Architect": [
    "AWS",
    "GCP",
    "Azure",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Kafka",
    "PostgreSQL",
    "Redis",
    "GraphQL",
    "REST API",
    "Python",
    "Go",
  ],
  "Systems Architect": [
    "AWS",
    "GCP",
    "Azure",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Kafka",
    "PostgreSQL",
    "Redis",
    "GraphQL",
    "REST API",
    "Python",
    "Go",
  ],
  "Database Administrator": [
    "PostgreSQL",
    "MySQL",
    "SQL Server",
    "Oracle",
    "MongoDB",
    "Redis",
    "AWS RDS",
    "GCP Cloud SQL",
    "Terraform",
    "Linux",
    "Python",
  ],
  "Embedded Engineer": [
    "C",
    "C++",
    "Rust",
    "MicroPython",
    "Arduino",
    "Raspberry Pi",
    "RTOS",
    "FPGA",
    "Verilog",
    "KiCad",
    "MATLAB",
  ],
  "Firmware Engineer": [
    "C",
    "C++",
    "Rust",
    "MicroPython",
    "Arduino",
    "Raspberry Pi",
    "RTOS",
    "FPGA",
    "Verilog",
    "KiCad",
    "MATLAB",
  ],
  "Game Developer": [
    "Unity",
    "Unreal Engine",
    "C#",
    "C++",
    "Blender",
    "Godot",
    "OpenGL",
    "DirectX",
    "Maya",
    "3ds Max",
  ],
  "Blockchain Engineer": [
    "Solidity",
    "Rust",
    "Go",
    "Ethereum",
    "Web3.js",
    "Hardhat",
    "Truffle",
    "Smart Contracts",
    "IPFS",
    "Node.js",
    "Python",
  ],
  "Developer Advocate": [
    "GitHub",
    "Markdown",
    "Notion",
    "Figma",
    "Lovable",
    "OBS",
    "YouTube",
    "Discord",
    "Slack",
  ],
  "Technical Writer": [
    "Markdown",
    "Notion",
    "Confluence",
    "GitHub",
    "Figma",
    "Lovable",
    "Google Docs",
    "Swagger",
    "YAML",
  ],
  "IT Support Engineer": [
    "Windows",
    "macOS",
    "Linux",
    "Active Directory",
    "Okta",
    "ServiceNow",
    "Jira",
    "Slack",
    "Microsoft 365",
    "Google Workspace",
    "Bash",
    "PowerShell",
  ],
};
