/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalEmailRouteImport } from './routes/legal.email'
import { Route as LegalDmcaRouteImport } from './routes/legal.dmca'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalBillingRouteImport } from './routes/legal.billing'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as GuidesGuideIndexRouteImport } from './routes/guides.$guide.index'
import { Route as GuidesGuideSlugRouteImport } from './routes/guides.$guide.$slug'
import { Route as ApiPublicHooksUnsubscribeRouteImport } from './routes/api/public/hooks/unsubscribe'
import { Route as ApiPublicHooksSweepResumeOrphansRouteImport } from './routes/api/public/hooks/sweep-resume-orphans'
import { Route as ApiPublicHooksQuizDraftSaveRouteImport } from './routes/api/public/hooks/quiz-draft-save'
import { Route as ApiPublicHooksPurgeQuizDraftsRouteImport } from './routes/api/public/hooks/purge-quiz-drafts'
import { Route as ApiPublicHooksPurgeDeletedAccountsRouteImport } from './routes/api/public/hooks/purge-deleted-accounts'
import { Route as ApiPublicHooksPostmarkWebhookRouteImport } from './routes/api/public/hooks/postmark-webhook'
import { Route as ApiPublicHooksConfirmEmailRouteImport } from './routes/api/public/hooks/confirm-email'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalEmailRoute = LegalEmailRouteImport.update({
  id: '/legal/email',
  path: '/legal/email',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDmcaRoute = LegalDmcaRouteImport.update({
  id: '/legal/dmca',
  path: '/legal/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBillingRoute = LegalBillingRouteImport.update({
  id: '/legal/billing',
  path: '/legal/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuidesGuideIndexRoute = GuidesGuideIndexRouteImport.update({
  id: '/guides/$guide/',
  path: '/guides/$guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideSlugRoute = GuidesGuideSlugRouteImport.update({
  id: '/guides/$guide/$slug',
  path: '/guides/$guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUnsubscribeRoute =
  ApiPublicHooksUnsubscribeRouteImport.update({
    id: '/api/public/hooks/unsubscribe',
    path: '/api/public/hooks/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSweepResumeOrphansRoute =
  ApiPublicHooksSweepResumeOrphansRouteImport.update({
    id: '/api/public/hooks/sweep-resume-orphans',
    path: '/api/public/hooks/sweep-resume-orphans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksQuizDraftSaveRoute =
  ApiPublicHooksQuizDraftSaveRouteImport.update({
    id: '/api/public/hooks/quiz-draft-save',
    path: '/api/public/hooks/quiz-draft-save',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeQuizDraftsRoute =
  ApiPublicHooksPurgeQuizDraftsRouteImport.update({
    id: '/api/public/hooks/purge-quiz-drafts',
    path: '/api/public/hooks/purge-quiz-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeDeletedAccountsRoute =
  ApiPublicHooksPurgeDeletedAccountsRouteImport.update({
    id: '/api/public/hooks/purge-deleted-accounts',
    path: '/api/public/hooks/purge-deleted-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostmarkWebhookRoute =
  ApiPublicHooksPostmarkWebhookRouteImport.update({
    id: '/api/public/hooks/postmark-webhook',
    path: '/api/public/hooks/postmark-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksConfirmEmailRoute =
  ApiPublicHooksConfirmEmailRouteImport.update({
    id: '/api/public/hooks/confirm-email',
    path: '/api/public/hooks/confirm-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/email': typeof LegalEmailRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/guides/$guide/$slug': typeof GuidesGuideSlugRoute
  '/guides/$guide/': typeof GuidesGuideIndexRoute
  '/api/public/hooks/confirm-email': typeof ApiPublicHooksConfirmEmailRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/purge-quiz-drafts': typeof ApiPublicHooksPurgeQuizDraftsRoute
  '/api/public/hooks/quiz-draft-save': typeof ApiPublicHooksQuizDraftSaveRoute
  '/api/public/hooks/sweep-resume-orphans': typeof ApiPublicHooksSweepResumeOrphansRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/email': typeof LegalEmailRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/guides/$guide/$slug': typeof GuidesGuideSlugRoute
  '/guides/$guide': typeof GuidesGuideIndexRoute
  '/api/public/hooks/confirm-email': typeof ApiPublicHooksConfirmEmailRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/purge-quiz-drafts': typeof ApiPublicHooksPurgeQuizDraftsRoute
  '/api/public/hooks/quiz-draft-save': typeof ApiPublicHooksQuizDraftSaveRoute
  '/api/public/hooks/sweep-resume-orphans': typeof ApiPublicHooksSweepResumeOrphansRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/legal/billing': typeof LegalBillingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/email': typeof LegalEmailRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/guides/$guide/$slug': typeof GuidesGuideSlugRoute
  '/guides/$guide/': typeof GuidesGuideIndexRoute
  '/api/public/hooks/confirm-email': typeof ApiPublicHooksConfirmEmailRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/api/public/hooks/purge-quiz-drafts': typeof ApiPublicHooksPurgeQuizDraftsRoute
  '/api/public/hooks/quiz-draft-save': typeof ApiPublicHooksQuizDraftSaveRoute
  '/api/public/hooks/sweep-resume-orphans': typeof ApiPublicHooksSweepResumeOrphansRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/tracker'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/legal/billing'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/dmca'
    | '/legal/email'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/blog/'
    | '/guides/'
    | '/guides/$guide/$slug'
    | '/guides/$guide/'
    | '/api/public/hooks/confirm-email'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/purge-quiz-drafts'
    | '/api/public/hooks/quiz-draft-save'
    | '/api/public/hooks/sweep-resume-orphans'
    | '/api/public/hooks/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/tracker'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/legal/billing'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/dmca'
    | '/legal/email'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/blog'
    | '/guides'
    | '/guides/$guide/$slug'
    | '/guides/$guide'
    | '/api/public/hooks/confirm-email'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/purge-quiz-drafts'
    | '/api/public/hooks/quiz-draft-save'
    | '/api/public/hooks/sweep-resume-orphans'
    | '/api/public/hooks/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/resume'
    | '/_authenticated/settings'
    | '/_authenticated/tracker'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/legal/billing'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/dmca'
    | '/legal/email'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/blog/'
    | '/guides/'
    | '/guides/$guide/$slug'
    | '/guides/$guide/'
    | '/api/public/hooks/confirm-email'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/api/public/hooks/purge-quiz-drafts'
    | '/api/public/hooks/quiz-draft-save'
    | '/api/public/hooks/sweep-resume-orphans'
    | '/api/public/hooks/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  LegalBillingRoute: typeof LegalBillingRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalDmcaRoute: typeof LegalDmcaRoute
  LegalEmailRoute: typeof LegalEmailRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  GuidesGuideSlugRoute: typeof GuidesGuideSlugRoute
  GuidesGuideIndexRoute: typeof GuidesGuideIndexRoute
  ApiPublicHooksConfirmEmailRoute: typeof ApiPublicHooksConfirmEmailRoute
  ApiPublicHooksPostmarkWebhookRoute: typeof ApiPublicHooksPostmarkWebhookRoute
  ApiPublicHooksPurgeDeletedAccountsRoute: typeof ApiPublicHooksPurgeDeletedAccountsRoute
  ApiPublicHooksPurgeQuizDraftsRoute: typeof ApiPublicHooksPurgeQuizDraftsRoute
  ApiPublicHooksQuizDraftSaveRoute: typeof ApiPublicHooksQuizDraftSaveRoute
  ApiPublicHooksSweepResumeOrphansRoute: typeof ApiPublicHooksSweepResumeOrphansRoute
  ApiPublicHooksUnsubscribeRoute: typeof ApiPublicHooksUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/email': {
      id: '/legal/email'
      path: '/legal/email'
      fullPath: '/legal/email'
      preLoaderRoute: typeof LegalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dmca': {
      id: '/legal/dmca'
      path: '/legal/dmca'
      fullPath: '/legal/dmca'
      preLoaderRoute: typeof LegalDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/billing': {
      id: '/legal/billing'
      path: '/legal/billing'
      fullPath: '/legal/billing'
      preLoaderRoute: typeof LegalBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guides/$guide/': {
      id: '/guides/$guide/'
      path: '/guides/$guide'
      fullPath: '/guides/$guide/'
      preLoaderRoute: typeof GuidesGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guide/$slug': {
      id: '/guides/$guide/$slug'
      path: '/guides/$guide/$slug'
      fullPath: '/guides/$guide/$slug'
      preLoaderRoute: typeof GuidesGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/unsubscribe': {
      id: '/api/public/hooks/unsubscribe'
      path: '/api/public/hooks/unsubscribe'
      fullPath: '/api/public/hooks/unsubscribe'
      preLoaderRoute: typeof ApiPublicHooksUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sweep-resume-orphans': {
      id: '/api/public/hooks/sweep-resume-orphans'
      path: '/api/public/hooks/sweep-resume-orphans'
      fullPath: '/api/public/hooks/sweep-resume-orphans'
      preLoaderRoute: typeof ApiPublicHooksSweepResumeOrphansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/quiz-draft-save': {
      id: '/api/public/hooks/quiz-draft-save'
      path: '/api/public/hooks/quiz-draft-save'
      fullPath: '/api/public/hooks/quiz-draft-save'
      preLoaderRoute: typeof ApiPublicHooksQuizDraftSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-quiz-drafts': {
      id: '/api/public/hooks/purge-quiz-drafts'
      path: '/api/public/hooks/purge-quiz-drafts'
      fullPath: '/api/public/hooks/purge-quiz-drafts'
      preLoaderRoute: typeof ApiPublicHooksPurgeQuizDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-deleted-accounts': {
      id: '/api/public/hooks/purge-deleted-accounts'
      path: '/api/public/hooks/purge-deleted-accounts'
      fullPath: '/api/public/hooks/purge-deleted-accounts'
      preLoaderRoute: typeof ApiPublicHooksPurgeDeletedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/postmark-webhook': {
      id: '/api/public/hooks/postmark-webhook'
      path: '/api/public/hooks/postmark-webhook'
      fullPath: '/api/public/hooks/postmark-webhook'
      preLoaderRoute: typeof ApiPublicHooksPostmarkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/confirm-email': {
      id: '/api/public/hooks/confirm-email'
      path: '/api/public/hooks/confirm-email'
      fullPath: '/api/public/hooks/confirm-email'
      preLoaderRoute: typeof ApiPublicHooksConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  LegalBillingRoute: LegalBillingRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalDmcaRoute: LegalDmcaRoute,
  LegalEmailRoute: LegalEmailRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  GuidesGuideSlugRoute: GuidesGuideSlugRoute,
  GuidesGuideIndexRoute: GuidesGuideIndexRoute,
  ApiPublicHooksConfirmEmailRoute: ApiPublicHooksConfirmEmailRoute,
  ApiPublicHooksPostmarkWebhookRoute: ApiPublicHooksPostmarkWebhookRoute,
  ApiPublicHooksPurgeDeletedAccountsRoute:
    ApiPublicHooksPurgeDeletedAccountsRoute,
  ApiPublicHooksPurgeQuizDraftsRoute: ApiPublicHooksPurgeQuizDraftsRoute,
  ApiPublicHooksQuizDraftSaveRoute: ApiPublicHooksQuizDraftSaveRoute,
  ApiPublicHooksSweepResumeOrphansRoute: ApiPublicHooksSweepResumeOrphansRoute,
  ApiPublicHooksUnsubscribeRoute: ApiPublicHooksUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
