CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  city text NOT NULL,
  state_code text NOT NULL,
  state_name text NOT NULL,
  label text NOT NULL UNIQUE,
  top100 boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX cities_state_code_idx ON public.cities (state_code);
CREATE INDEX cities_top100_idx ON public.cities (top100);
GRANT SELECT ON public.cities TO anon, authenticated;
GRANT ALL ON public.cities TO service_role;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cities are readable by everyone" ON public.cities FOR SELECT USING (true);
INSERT INTO public.cities (city, state_code, state_name, label, top100) VALUES
('Huntsville','AL','Alabama','Huntsville, AL',false),
('Birmingham','AL','Alabama','Birmingham, AL',false),
('Montgomery','AL','Alabama','Montgomery, AL',false),
('Anchorage','AK','Alaska','Anchorage, AK',true),
('Fairbanks','AK','Alaska','Fairbanks, AK',false),
('Juneau','AK','Alaska','Juneau, AK',false),
('Phoenix','AZ','Arizona','Phoenix, AZ',true),
('Tucson','AZ','Arizona','Tucson, AZ',true),
('Mesa','AZ','Arizona','Mesa, AZ',true),
('Chandler','AZ','Arizona','Chandler, AZ',true),
('Gilbert','AZ','Arizona','Gilbert, AZ',true),
('Glendale','AZ','Arizona','Glendale, AZ',true),
('Scottsdale','AZ','Arizona','Scottsdale, AZ',true),
('Little Rock','AR','Arkansas','Little Rock, AR',false),
('Fayetteville','AR','Arkansas','Fayetteville, AR',false),
('Fort Smith','AR','Arkansas','Fort Smith, AR',false),
('Los Angeles','CA','California','Los Angeles, CA',true),
('San Diego','CA','California','San Diego, CA',true),
('San Jose','CA','California','San Jose, CA',true),
('San Francisco','CA','California','San Francisco, CA',true),
('Fresno','CA','California','Fresno, CA',true),
('Sacramento','CA','California','Sacramento, CA',true),
('Long Beach','CA','California','Long Beach, CA',true),
('Oakland','CA','California','Oakland, CA',true),
('Bakersfield','CA','California','Bakersfield, CA',true),
('Anaheim','CA','California','Anaheim, CA',true),
('Riverside','CA','California','Riverside, CA',true),
('Santa Ana','CA','California','Santa Ana, CA',true),
('Stockton','CA','California','Stockton, CA',true),
('Irvine','CA','California','Irvine, CA',true),
('Chula Vista','CA','California','Chula Vista, CA',true),
('Fremont','CA','California','Fremont, CA',true),
('Denver','CO','Colorado','Denver, CO',true),
('Colorado Springs','CO','Colorado','Colorado Springs, CO',true),
('Aurora','CO','Colorado','Aurora, CO',true),
('Bridgeport','CT','Connecticut','Bridgeport, CT',false),
('Stamford','CT','Connecticut','Stamford, CT',false),
('New Haven','CT','Connecticut','New Haven, CT',false),
('Wilmington','DE','Delaware','Wilmington, DE',false),
('Dover','DE','Delaware','Dover, DE',false),
('Newark','DE','Delaware','Newark, DE',false),
('Washington','DC','District of Columbia','Washington, DC',true),
('Jacksonville','FL','Florida','Jacksonville, FL',true),
('Miami','FL','Florida','Miami, FL',true),
('Tampa','FL','Florida','Tampa, FL',true),
('Orlando','FL','Florida','Orlando, FL',true),
('St. Petersburg','FL','Florida','St. Petersburg, FL',true),
('Atlanta','GA','Georgia','Atlanta, GA',true),
('Columbus','GA','Georgia','Columbus, GA',false),
('Augusta','GA','Georgia','Augusta, GA',false),
('Honolulu','HI','Hawaii','Honolulu, HI',true),
('Pearl City','HI','Hawaii','Pearl City, HI',false),
('Hilo','HI','Hawaii','Hilo, HI',false),
('Boise','ID','Idaho','Boise, ID',true),
('Meridian','ID','Idaho','Meridian, ID',false),
('Nampa','ID','Idaho','Nampa, ID',false),
('Chicago','IL','Illinois','Chicago, IL',true),
('Aurora','IL','Illinois','Aurora, IL',false),
('Joliet','IL','Illinois','Joliet, IL',false),
('Indianapolis','IN','Indiana','Indianapolis, IN',true),
('Fort Wayne','IN','Indiana','Fort Wayne, IN',true),
('Evansville','IN','Indiana','Evansville, IN',false),
('Des Moines','IA','Iowa','Des Moines, IA',false),
('Cedar Rapids','IA','Iowa','Cedar Rapids, IA',false),
('Davenport','IA','Iowa','Davenport, IA',false),
('Wichita','KS','Kansas','Wichita, KS',true),
('Overland Park','KS','Kansas','Overland Park, KS',false),
('Kansas City','KS','Kansas','Kansas City, KS',false),
('Louisville','KY','Kentucky','Louisville, KY',true),
('Lexington','KY','Kentucky','Lexington, KY',true),
('Bowling Green','KY','Kentucky','Bowling Green, KY',false),
('New Orleans','LA','Louisiana','New Orleans, LA',true),
('Baton Rouge','LA','Louisiana','Baton Rouge, LA',true),
('Shreveport','LA','Louisiana','Shreveport, LA',false),
('Portland','ME','Maine','Portland, ME',false),
('Lewiston','ME','Maine','Lewiston, ME',false),
('Bangor','ME','Maine','Bangor, ME',false),
('Baltimore','MD','Maryland','Baltimore, MD',true),
('Frederick','MD','Maryland','Frederick, MD',false),
('Gaithersburg','MD','Maryland','Gaithersburg, MD',false),
('Boston','MA','Massachusetts','Boston, MA',true),
('Worcester','MA','Massachusetts','Worcester, MA',false),
('Springfield','MA','Massachusetts','Springfield, MA',false),
('Detroit','MI','Michigan','Detroit, MI',true),
('Grand Rapids','MI','Michigan','Grand Rapids, MI',false),
('Warren','MI','Michigan','Warren, MI',false),
('Minneapolis','MN','Minnesota','Minneapolis, MN',true),
('St. Paul','MN','Minnesota','St. Paul, MN',true),
('Rochester','MN','Minnesota','Rochester, MN',false),
('Jackson','MS','Mississippi','Jackson, MS',false),
('Gulfport','MS','Mississippi','Gulfport, MS',false),
('Southaven','MS','Mississippi','Southaven, MS',false),
('Kansas City','MO','Missouri','Kansas City, MO',true),
('St. Louis','MO','Missouri','St. Louis, MO',true),
('Springfield','MO','Missouri','Springfield, MO',false),
('Billings','MT','Montana','Billings, MT',false),
('Missoula','MT','Montana','Missoula, MT',false),
('Great Falls','MT','Montana','Great Falls, MT',false),
('Omaha','NE','Nebraska','Omaha, NE',true),
('Lincoln','NE','Nebraska','Lincoln, NE',true),
('Bellevue','NE','Nebraska','Bellevue, NE',false),
('Las Vegas','NV','Nevada','Las Vegas, NV',true),
('Henderson','NV','Nevada','Henderson, NV',true),
('Reno','NV','Nevada','Reno, NV',true),
('North Las Vegas','NV','Nevada','North Las Vegas, NV',true),
('Manchester','NH','New Hampshire','Manchester, NH',false),
('Nashua','NH','New Hampshire','Nashua, NH',false),
('Concord','NH','New Hampshire','Concord, NH',false),
('Newark','NJ','New Jersey','Newark, NJ',true),
('Jersey City','NJ','New Jersey','Jersey City, NJ',true),
('Paterson','NJ','New Jersey','Paterson, NJ',false),
('Albuquerque','NM','New Mexico','Albuquerque, NM',true),
('Las Cruces','NM','New Mexico','Las Cruces, NM',false),
('Rio Rancho','NM','New Mexico','Rio Rancho, NM',false),
('New York City','NY','New York','New York City, NY',true),
('Buffalo','NY','New York','Buffalo, NY',true),
('Yonkers','NY','New York','Yonkers, NY',false),
('Charlotte','NC','North Carolina','Charlotte, NC',true),
('Raleigh','NC','North Carolina','Raleigh, NC',true),
('Greensboro','NC','North Carolina','Greensboro, NC',true),
('Durham','NC','North Carolina','Durham, NC',true),
('Winston-Salem','NC','North Carolina','Winston-Salem, NC',true),
('Fargo','ND','North Dakota','Fargo, ND',false),
('Bismarck','ND','North Dakota','Bismarck, ND',false),
('Grand Forks','ND','North Dakota','Grand Forks, ND',false),
('Columbus','OH','Ohio','Columbus, OH',true),
('Cleveland','OH','Ohio','Cleveland, OH',true),
('Cincinnati','OH','Ohio','Cincinnati, OH',true),
('Toledo','OH','Ohio','Toledo, OH',true),
('Oklahoma City','OK','Oklahoma','Oklahoma City, OK',true),
('Tulsa','OK','Oklahoma','Tulsa, OK',true),
('Norman','OK','Oklahoma','Norman, OK',false),
('Portland','OR','Oregon','Portland, OR',true),
('Eugene','OR','Oregon','Eugene, OR',false),
('Salem','OR','Oregon','Salem, OR',false),
('Philadelphia','PA','Pennsylvania','Philadelphia, PA',true),
('Pittsburgh','PA','Pennsylvania','Pittsburgh, PA',true),
('Allentown','PA','Pennsylvania','Allentown, PA',false),
('Providence','RI','Rhode Island','Providence, RI',false),
('Cranston','RI','Rhode Island','Cranston, RI',false),
('Warwick','RI','Rhode Island','Warwick, RI',false),
('Charleston','SC','South Carolina','Charleston, SC',false),
('Columbia','SC','South Carolina','Columbia, SC',false),
('North Charleston','SC','South Carolina','North Charleston, SC',false),
('Sioux Falls','SD','South Dakota','Sioux Falls, SD',false),
('Rapid City','SD','South Dakota','Rapid City, SD',false),
('Aberdeen','SD','South Dakota','Aberdeen, SD',false),
('Nashville','TN','Tennessee','Nashville, TN',true),
('Memphis','TN','Tennessee','Memphis, TN',true),
('Knoxville','TN','Tennessee','Knoxville, TN',false),
('Houston','TX','Texas','Houston, TX',true),
('San Antonio','TX','Texas','San Antonio, TX',true),
('Dallas','TX','Texas','Dallas, TX',true),
('Fort Worth','TX','Texas','Fort Worth, TX',true),
('Austin','TX','Texas','Austin, TX',true),
('El Paso','TX','Texas','El Paso, TX',true),
('Arlington','TX','Texas','Arlington, TX',true),
('Corpus Christi','TX','Texas','Corpus Christi, TX',true),
('Plano','TX','Texas','Plano, TX',true),
('Laredo','TX','Texas','Laredo, TX',true),
('Lubbock','TX','Texas','Lubbock, TX',true),
('Irving','TX','Texas','Irving, TX',true),
('Garland','TX','Texas','Garland, TX',true),
('Frisco','TX','Texas','Frisco, TX',true),
('Salt Lake City','UT','Utah','Salt Lake City, UT',false),
('West Valley City','UT','Utah','West Valley City, UT',false),
('West Jordan','UT','Utah','West Jordan, UT',false),
('Burlington','VT','Vermont','Burlington, VT',false),
('South Burlington','VT','Vermont','South Burlington, VT',false),
('Rutland','VT','Vermont','Rutland, VT',false),
('Virginia Beach','VA','Virginia','Virginia Beach, VA',true),
('Chesapeake','VA','Virginia','Chesapeake, VA',true),
('Norfolk','VA','Virginia','Norfolk, VA',true),
('Richmond','VA','Virginia','Richmond, VA',true),
('Seattle','WA','Washington','Seattle, WA',true),
('Spokane','WA','Washington','Spokane, WA',true),
('Tacoma','WA','Washington','Tacoma, WA',false),
('Charleston','WV','West Virginia','Charleston, WV',false),
('Huntington','WV','West Virginia','Huntington, WV',false),
('Morgantown','WV','West Virginia','Morgantown, WV',false),
('Milwaukee','WI','Wisconsin','Milwaukee, WI',true),
('Madison','WI','Wisconsin','Madison, WI',true),
('Green Bay','WI','Wisconsin','Green Bay, WI',false),
('Cheyenne','WY','Wyoming','Cheyenne, WY',false),
('Casper','WY','Wyoming','Casper, WY',false),
('Laramie','WY','Wyoming','Laramie, WY',false);